# FILE: util/config.py

# Configuration variables

## DAQ configuration
USE_MOCK_DATA = True
HEADER_VALUE = 0xAA
TERMINATOR_VALUE = 0xFF
SAMPLING_RATE = 8000
CHANNELS_NUMBER = 4
BITS_PER_SAMPLE = 24  # 19 bits
HEADER_LEN = 1
TERM_LEN = 1
SAMPLES_PER_PACKAGE = 2
CONVERTED_RAW_DATA_BUFFER_SIZE = 10000
VREF = 2.4
GAIN = 12

## Filter configuration
HIGH_PASS_FILTER = 0.0001
LOW_PASS_FILTER = 3800
FILTER_ORDER = 4
NOTCH_FILTER = 50
GAIN = 1

## Record configuration
# "mat" for MATLAB .mat file
# "h5" for HDF5 file
RECORD_FORMAT = "mat"