# FILE: util/config.py

# Configuration variables
CHANNELS_NUMBER = 8
BYTES_PER_SAMPLE = 3  # 24 bits
HEADER_LEN = 1
TERM_LEN = 1
VREF = 2.4
GAIN = 12
UNCONVERTED_RAW_DATA_BUFFER_SIZE = 80000
CONVERTED_RAW_DATA_BUFFER_SIZE = 10000